name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish port to WinGet
        uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: kevinboss.port
          installers-regex: '\${{ steps.build-data.outputs.release_name }}.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
          release-tag: ${{ steps.build-data.outputs.tag }}
          delete-previous-version: false