name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish port to WinGet
        uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: kevinboss.port
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
          delete-previous-version: false